import { defineStore } from "pinia";

export const useArticlesStore = defineStore("articlesStore", {
  state: () => ({
    articles: [
      {
        id: 1,
        title: "Modern Python Environments",
        subtitle: "Dependency and workspace management",
        abstract: "test",
        text: '<p>Once you get through the pain of setting up a Python environment for a single "hello world"-esque application, you\'ll need to go through an even more difficult process of figuring out how to manage multiple environments for multiple Python projects. Some of the projects could be new while others are stale piles of code from ten years ago. Fortunately, there a number of tools available to help make dependency and workspace management easier.</p><p>Once you get through the pain of setting up a Python environment for a single "hello world"-esque application, you\'ll need to go through an even more difficult process of figuring out how to manage multiple environments for multiple Python projects. Some of the projects could be new while others are stale piles of code from ten years ago. Fortunately, there a number of tools available to help make dependency and workspace management easier.</p><p>Once you get through the pain of setting up a Python environment for a single "hello world"-esque application, you\'ll need to go through an even more difficult process of figuring out how to manage multiple environments for multiple Python projects. Some of the projects could be new while others are stale piles of code from ten years ago. Fortunately, there a number of tools available to help make dependency and workspace management easier.</p>',
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 2,
        title: "Modern Python Environments",
        subtitle: "Dependency and workspace management",
        abstract: "## Dependency and workspace management",
        text: "## Dependency and workspace management",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 3,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 4,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 5,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 6,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 7,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 8,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 9,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
    ],
  }),
  getters: {
    article: (state) => state.articles,
    articleById: (state) => (articleId) =>
      state.articles.find((article) => article.id == articleId),
  },
});
