import { defineStore } from "pinia";

export const useArticlesStore = defineStore("articlesStore", {
  state: () => ({
    articles: [
      {
        id: 1,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 2,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 3,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 4,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 5,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 6,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 7,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 8,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
      {
        id: 9,
        title: "t",
        subtitle: "T",
        abstract: "test",
        text: "test",
        date: "March, 2 2022",
        author: "Daniel",
        tags: ["tag1", "tag2", "tag3"],
      },
    ],
  }),
  actions: {},
  getters: {
    articles: (state) => state.articles,
    getArticleById: (state) => {
      return (id) => state.articles.find((article) => article.id === id);
    },
  },
});
